# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestClientSDk' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestClientSDk
  pod 'NexmoClient'

  target 'TestClientSDkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestClientSDkUITests' do
    # Pods for testing
  end

end
